spring:
  application:
    name: demoservice
  data:
    rest:
      base-path: /api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/demoservice
    username: sa
    password:
  liquibase:
    enabled: true
    user: sa
    password:
    change-log: classpath:/db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console